import { Container } from "./components/ui/container";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

import Providers from "./components/Providers";
import Navbar from "./components/Navbar";
import Search from "./components/Search";

export const metadata = {
  title: "Dictionary App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <Container>
            <Navbar />
            <Search />
            {children}
          </Container>
        </Providers>
      </body>
    </html>
  );
}
